import { useEffect, useMemo, useState } from "react";
import * as UI from "@proshore/ui";
import { Badge, Button, Eyebrow, Note, Page, PageHeader, SearchField, SimpleTable, Text, toast } from "@proshore/ui";
import api from "../generated/api.json";

/** Generated by packages/ui/scripts/gen-api.mjs from the real source (props, defaults and descriptions come from the code and its JSDoc). */
type Prop = { name: string; type: string; required: boolean; default: string | null; description: string };
type Entry = { name: string; kind: string; area: string; description: string; props: Prop[]; definition: string | null; file: string; snippet: string; snippetSource: string; notes: string[] };
const entries = api.exports as Entry[];

const AREAS = ["Layout", "Actions", "Forms", "Tables", "Charts", "Overlays", "Shell", "Auth-free UI", "Icons", "Hooks and types"] as const;

/** Hand-kept: the gallery page that demos a component. Anything missing simply has no demo link. */
const DEMOS: Record<string, string> = {
  AppShell: "/shell", AssistantPanel: "/shell", CommandPalette: "/shell", ShellNav: "/shell", SherpaGuide: "/shell", UserMenu: "/shell", WorkspaceSwitcher: "/shell", DemoTag: "/shell",
  Avatar: "/brand", PrayerFlags: "/brand", ProshoreIcon: "/brand", ProshoreWordmark: "/brand", Ridgeline: "/brand",
  Badge: "/layout", Breadcrumbs: "/layout", Disclosure: "/layout", Grid: "/layout", KeyValue: "/layout", Note: "/layout", Panel: "/layout", Section: "/layout", StatCard: "/layout", Stepper: "/layout", Tabs: "/layout", Timeline: "/layout", toast: "/layout",
  Stack: "/layout", Cluster: "/layout", Page: "/layout", PageHeader: "/layout",
  Button: "/actions", IconButton: "/actions", Tooltip: "/actions", Text: "/foundations", Heading: "/foundations",
  BarChart: "/charts", ChartCard: "/charts", Legend: "/charts", Sparkline: "/charts", StackedBar: "/charts", TrendLine: "/charts",
  Checkbox: "/forms", DateRangePicker: "/forms", LocaleProvider: "/forms", MultiSelect: "/forms", RadioGroup: "/forms", SearchField: "/forms", Select: "/forms", Switch: "/forms", TextArea: "/forms", TextField: "/forms",
  DataTable: "/tables", EmptyState: "/tables", ErrorState: "/tables", SimpleTable: "/tables", TableSkeleton: "/tables",
  SlideGroup: "/overlays", SlideOver: "/overlays",
  ConfirmDialog: "/dialogs", ModalDialog: "/dialogs", FileDropzone: "/dialogs", KanbanBoard: "/dialogs", Pagination: "/dialogs", StatusPage: "/dialogs",
  SignInScreen: "/sign-in",
};
const DEMO_LABEL: Record<string, string> = { "/shell": "App shell", "/brand": "Brand and icons", "/layout": "Layout and feedback", "/actions": "Actions", "/foundations": "Foundations", "/charts": "Charts", "/forms": "Forms", "/tables": "Tables", "/overlays": "Overlays and menus", "/dialogs": "Dialogs and boards", "/sign-in": "Sign in" };

async function copy(text: string) {
  try { await navigator.clipboard.writeText(text); toast.show("Copied", { tone: "success" }); return; } catch { /* fall back below */ }
  try {
    const ta = document.createElement("textarea");
    ta.value = text; ta.setAttribute("readonly", ""); ta.style.position = "fixed"; ta.style.opacity = "0";
    document.body.appendChild(ta); ta.select();
    const ok = document.execCommand("copy"); document.body.removeChild(ta);
    toast.show(ok ? "Copied" : "Select the snippet and copy it by hand", { tone: ok ? "success" : "warning" });
  } catch { toast.show("Select the snippet and copy it by hand", { tone: "warning" }); }
}

const jumpTo = (name: string) => {
  const el = document.getElementById(`api-${name}`);
  if (!el) return;
  el.scrollIntoView({ block: "start" });
  el.focus({ preventScroll: true });
};

function Snippet({ entry }: { entry: Entry }) {
  return (
    <div className="g-api__snippet">
      <pre tabIndex={0} aria-label={`${entry.name} usage example`}><code>{entry.snippet}</code></pre>
      <Button size="1" variant="outline" onClick={() => copy(entry.snippet)} aria-label={`Copy ${entry.name} usage example`}>Copy</Button>
    </div>
  );
}

function Card({ entry }: { entry: Entry }) {
  const demo = DEMOS[entry.name];
  return (
    <article className="g-api__card" id={`api-${entry.name}`} tabIndex={-1} aria-labelledby={`api-h-${entry.name}`}>
      <header className="g-api__head">
        <h3 id={`api-h-${entry.name}`}><code>{entry.name}</code></h3>
        <Badge color="gray">{entry.kind}</Badge>
        {entry.snippetSource === "synthesised" && entry.kind === "component" && <Badge color="amber" variant="outline">generated snippet</Badge>}
      </header>
      {entry.description ? <Text as="p" size="2">{entry.description}</Text> : entry.kind !== "type" && <Text as="p" size="2" color="gray">No description in the source yet.</Text>}
      <Text as="p" size="1" color="gray" className="g-api__meta">
        <code>{entry.file}</code>{demo && <> · <a href={`#${demo}`}>Demo: {DEMO_LABEL[demo]}</a></>}
      </Text>
      {entry.definition && <pre className="g-api__def" tabIndex={0} aria-label={`${entry.name} definition`}><code>{entry.definition}</code></pre>}
      {entry.props.length > 0 && (
        <SimpleTable
          caption={`${entry.name} ${entry.kind === "type" ? "fields" : entry.kind === "component" ? "props" : "parameters"}`}
          rows={entry.props} getRowId={(p) => p.name}
          columns={[
            { id: "name", header: "Name", cell: (p) => <code>{p.name}{p.required ? <span className="g-api__req" title="Required"> *<span className="pr-sr"> (required)</span></span> : null}</code> },
            { id: "type", header: "Type", cell: (p) => <code className="g-api__type">{p.type}</code> },
            { id: "default", header: "Default", cell: (p) => (p.default ? <code>{p.default}</code> : <span aria-label="none">-</span>) },
            { id: "description", header: "Description", cell: (p) => p.description || <span aria-label="none">-</span> },
          ]}
        />
      )}
      {entry.notes.map((n) => <Text as="p" size="1" color="gray" key={n}>Note: {n}.</Text>)}
      {entry.kind !== "type" && <Snippet entry={entry} />}
    </article>
  );
}

const iconComponents = UI as unknown as Record<string, React.ComponentType | undefined>;
function IconGrid({ list }: { list: Entry[] }) {
  return (
    <ul className="g-api__icons" aria-label="Icons">
      {list.map((e) => { const I = iconComponents[e.name]; return (
        <li key={e.name} id={`api-${e.name}`} tabIndex={-1}>{I && <I aria-hidden />}<code>{e.name}</code></li>
      ); })}
    </ul>
  );
}

export function ApiPage() {
  const [q, setQ] = useState("");
  const [indexOpen, setIndexOpen] = useState(() => window.matchMedia("(min-width: 900px)").matches);
  const needle = q.trim().toLowerCase();
  const shown = useMemo(() => (needle ? entries.filter((e) => [e.name, e.description, e.area, ...e.props.flatMap((p) => [p.name, p.description])].some((s) => s.toLowerCase().includes(needle))) : entries), [needle]);
  const groups = AREAS.map((a) => ({ area: a, list: shown.filter((e) => e.area === a) })).filter((g) => g.list.length);
  useEffect(() => { document.title = "API reference · Design system"; }, []);
  const counts = useMemo(() => ({ components: entries.filter((e) => e.kind === "component" && e.area !== "Icons").length, props: entries.reduce((n, e) => n + e.props.length, 0) }), []);

  return (
    <Page>
      <PageHeader eyebrow="Reference" title="API reference"
        description={`Every export of @proshore/ui with its props, defaults, types and description. Generated from the source and its JSDoc on every build, so it cannot drift. ${entries.length} exports, ${counts.components} components, ${counts.props} props and fields.`} />
      <div className="g-api">
        <aside className="g-api__index" aria-label="API index">
          <details open={indexOpen} onToggle={(e) => setIndexOpen(e.currentTarget.open)}>
            <summary>Index</summary>
            <nav aria-label="API index sections">
              {groups.map((g) => (
                <div key={g.area}>
                  <Eyebrow>{g.area}</Eyebrow>
                  {g.area === "Icons" ? <ul><li><a href="#/api" onClick={(ev) => { ev.preventDefault(); document.getElementById("api-area-Icons")?.scrollIntoView(); }}>{g.list.length} icons</a></li></ul> : (
                    <ul>{g.list.map((e) => <li key={e.name}><a href="#/api" onClick={(ev) => { ev.preventDefault(); jumpTo(e.name); }}>{e.name}</a></li>)}</ul>
                  )}
                </div>
              ))}
            </nav>
          </details>
        </aside>
        <div className="g-api__main">
          <SearchField label="Search the API" hideLabel={false} value={q} onChange={setQ} placeholder="Name, description or prop, for example Pagination" />
          <div role="status" aria-live="polite" className="g-api__count"><Text size="2" color="gray">{shown.length} of {entries.length} exports</Text></div>
          {groups.length === 0 && <Note tone="info">Nothing matches “{q}”. Try a component name or a prop name.</Note>}
          {groups.map((g) => (
            <section key={g.area} aria-labelledby={`api-area-${g.area}`} className="g-api__group">
              <h2 id={`api-area-${g.area}`} tabIndex={-1}>{g.area}</h2>
              {g.area === "Icons" ? (
                <>
                  <Text as="p" size="2">Radix icons on a 15px grid in <code>currentColor</code>. They accept all SVG props; <code>width</code> and <code>height</code> default to 15. Always hide decorative icons with <code>aria-hidden</code>.</Text>
                  <Snippet entry={{ ...g.list[0], name: "Icons", snippet: `<${g.list[0].name} aria-hidden />` }} />
                  <IconGrid list={g.list} />
                </>
              ) : g.list.map((e) => <Card key={e.name} entry={e} />)}
            </section>
          ))}
        </div>
      </div>
    </Page>
  );
}
