import { Badge, Button, Disclosure, Note, Tabs, Text, toast } from "@proshore/ui";
import { CheckIcon } from "@proshore/ui";
import { SherpaGuide } from "@proshore/ui";
import { useEffect, useState } from "react";
import { EvidenceTrail, trailOf } from "./EvidenceTrail";
import type { FindingRecord, ReviewState } from "../fixtures/brightfield";
import { KeyValue } from "@proshore/ui";
import { SlideGroup, SlideOver } from "@proshore/ui";
import { Timeline } from "@proshore/ui";
import type { TimelineEntry } from "@proshore/ui";
import { EvidenceBadge, SeverityBadge } from "../ui";

const reviewLabel: Record<ReviewState, string> = { unreviewed: "Not reviewed", "needs-review": "Needs review", confirmed: "Confirmed", disputed: "Disputed" };
const reviewColor: Record<ReviewState, "gray" | "amber" | "green" | "red"> = { unreviewed: "gray", "needs-review": "amber", confirmed: "green", disputed: "red" };

/** Demo history derived from the record. Real history would come from review records. */
function historyOf(f: FindingRecord) {
  const h: TimelineEntry[] = [{ id: "h1", when: "22 Sep 2026", actor: `Scan ${f.technical.scan}`, text: `Reported by ${f.security.tools.join(", ")}.`, kind: "observed" }];
  if (f.reviewState === "confirmed") h.unshift({ id: "h2", when: "24 Sep 2026", actor: "Sanne de Vries (Technical lead)", text: "Confirmed after workshop.", kind: "review" });
  if (f.reviewState === "disputed") h.unshift({ id: "h3", when: "25 Sep 2026", actor: "Anouk Bakker (Business owner)", text: "Disputed: this step is not used in production.", kind: "review" });
  return h;
}

/** Finding detail as a slide-over. On screens of 1440px or wider it docks beside the list (the table stays usable); below that it is modal. Header = identity and status; body = summary, three perspectives, trail, history; footer = actions. */
export function FindingSlideOver({ list, index, onIndex, onClose, onAsk }: {
  list: FindingRecord[]; index: number | null; onIndex: (i: number) => void; onClose: () => void; onAsk: (f: FindingRecord) => void;
}) {
  const f = index === null ? null : list[index] ?? null;
  const [done, setDone] = useState<Record<string, boolean>>({});
  const [tab, setTab] = useState("business");
  useEffect(() => setTab("business"), [f?.id]);
  return (
    <SlideOver
      dock open={!!f} onOpenChange={(o) => !o && onClose()}
      eyebrow={f ? `${f.id} · ${f.category}` : ""} title={f?.title ?? ""}
      chips={f && (<><SeverityBadge severity={f.severity} /><EvidenceBadge state={f.state} /><Badge variant="soft" color={reviewColor[done[f.id] ? "confirmed" : f.reviewState]} size="2">{reviewLabel[done[f.id] ? "confirmed" : f.reviewState]}</Badge></>)}
      nav={index === null ? undefined : { index, total: list.length, onPrev: () => onIndex(index - 1), onNext: () => onIndex(index + 1) }}
      footer={f && (<>
        <Button variant="outline" onClick={() => onAsk(f)}><SherpaGuide size={20} /> Ask Sherpa about this</Button>
        <Button disabled={done[f.id]} onClick={() => { setDone((d) => ({ ...d, [f.id]: true })); toast.show(`${f.id} marked as reviewed (demo)`, { tone: "success" }); }}><CheckIcon aria-hidden /> {done[f.id] ? "Marked as reviewed (demo)" : "Mark as reviewed"}</Button>
      </>)}
    >
      {f && (<>
        <div className="so__summary">
          <p className="so__lead">{f.business.meaning}</p>
          <p className="so__sub">{f.state === "confirmed" ? "Checked by a named reviewer." : f.state === "observed" ? `Reported by ${f.security.tools.length} tool${f.security.tools.length > 1 ? "s" : ""}. Not proof it can be exploited.` : "Generated by Sherpa. Not yet checked."} {f.reviewNote}.</p>
        </div>
        <SlideGroup title="Where this comes from">
          <EvidenceTrail bare steps={trailOf(f)} />
        </SlideGroup>
        {f.state !== "confirmed" && <Note tone="warning">{f.severity === "critical" || f.severity === "high" ? "Not known yet: whether this can actually be exploited in your setup. A person needs to check." : "Not confirmed by a person yet."} {f.security.disposition}.</Note>}
        <SlideGroup title="Perspectives">
          <Tabs label="Perspective" value={tab} onChange={setTab} items={[
            { id: "business", label: "Business", content: <KeyValue items={[{ label: "Capability", value: <>{f.business.capability} <EvidenceBadge state={f.business.state} /></> }, { label: "Application", value: f.appId[0].toUpperCase() + f.appId.slice(1) }, { label: "Journey step", value: f.capability }]} /> },
            { id: "security", label: "Security", content: (<>
              <KeyValue items={[{ label: "Reported by", value: f.security.tools.join(", ") }, { label: "Weakness", value: f.security.cwe }, { label: "Corroborated", value: f.security.corroborated ? "Yes, by more than one tool" : "No" }, { label: "Disposition", value: f.security.disposition }]} />
              <div style={{ marginTop: "var(--space-3)" }}><Note tone="info">{f.security.note}</Note></div></>) },
            { id: "technical", label: "Technical", content: <KeyValue items={[{ label: "Location", value: <code>{f.technical.file}:{f.technical.line}</code> }, { label: "Package", value: `${f.technical.pkg} ${f.technical.installed}` }, { label: "Fixed in", value: f.technical.fixed }, { label: "Scan", value: f.technical.scan }, { label: "Source revision", value: f.technical.revision }, { label: "Fingerprint", value: <code>{f.technical.fingerprint}</code> }]} /> },
          ]} />
        </SlideGroup>
        <Disclosure title="Review history">
          <Timeline entries={historyOf(f)} />
        </Disclosure>
      </>)}
    </SlideOver>
  );
}


/** Gallery trigger for the pattern page. */
export function FindingDrawer() {
  const [open, setOpen] = useState(false);
  return (
    <>
      <Button variant="outline" onClick={() => setOpen(true)}>Open finding as slide-over</Button>
      <FindingSlideOver list={[]} index={null} onIndex={() => {}} onClose={() => {}} onAsk={() => {}} />
      <GalleryOpen open={open} onClose={() => setOpen(false)} />
    </>
  );
}
import { findings } from "../fixtures/brightfield";
function GalleryOpen({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [i, setI] = useState(0);
  return <FindingSlideOver list={findings} index={open ? i : null} onIndex={setI} onClose={onClose} onAsk={() => {}} />;
}
