// Exports the --pr-* primitives from tokens.css to tokens/tokens.json (design-token style: name -> { value }).
// A designer (for example via Figma Tokens Studio) can import this file later. Code stays the source of truth.
import { readFileSync, writeFileSync } from "node:fs";
const css = readFileSync(new URL("../src/theme/tokens.css", import.meta.url), "utf8");
const root = css.slice(css.indexOf(":root"), css.indexOf("}", css.indexOf(":root")));
const colors = {};
for (const m of root.matchAll(/--pr-([a-z0-9-]+):\s*(#[0-9a-fA-F]{3,8})\s*;/g)) colors[m[1]] = { value: m[2].toLowerCase(), type: "color" };
const out = { $description: "Proshore primitives (from the Relume variables on proshore.eu, verified against Webflow 29 Sep 2026). Generated by scripts/export-tokens.mjs.", color: colors };
writeFileSync(new URL("../tokens/tokens.json", import.meta.url), JSON.stringify(out, null, 2) + "\n");
console.log(`Exported ${Object.keys(colors).length} colour tokens`);
