// Generates the component API reference from the real source:  node scripts/gen-api.mjs [outFile]
// Default output: apps/gallery/src/generated/api.json (not committed, regenerated by the gallery's predev/prebuild/typecheck).
// Uses the TypeScript compiler API (checker) through the `typescript5` alias: the main `typescript` is 7.x (native port), which has no stable JS API.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript5";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = join(root, "src");
const out = resolve(process.argv[2] ?? join(root, "../../apps/gallery/src/generated/api.json"));

const cfgPath = join(root, "tsconfig.json");
const cfg = ts.parseJsonConfigFileContent(ts.readConfigFile(cfgPath, ts.sys.readFile).config, ts.sys, root);
const program = ts.createProgram({ rootNames: [join(srcDir, "index.ts")], options: { ...cfg.options, types: [] } });
const checker = program.getTypeChecker();
const entry = program.getSourceFile(join(srcDir, "index.ts"));
const isOurs = (d) => d && !d.getSourceFile().isDeclarationFile && d.getSourceFile().fileName.startsWith(srcDir);
const rel = (d) => relative(srcDir, d.getSourceFile().fileName).replace(/\\/g, "/");
const clean = (s) => s.replace(/\s+/g, " ").trim();

/** First paragraph of the JSDoc, as one line. */
const firstParagraph = (symbol) => clean(ts.displayPartsToString(symbol.getDocumentationComment(checker)).split(/\n\s*\n/)[0] ?? "");
const exampleOf = (symbol) => {
  const tag = symbol.getJsDocTags(checker).find((t) => t.name === "example");
  if (!tag) return "";
  return ts.displayPartsToString(tag.text ?? []).replace(/^```\w*\n?|\n?```$/g, "").replace(/^\n+|\s+$/g, "");
};

/** Declaration that carries the code (function, variable, class, type, interface) behind an exported (possibly aliased) symbol. */
const resolveSymbol = (s) => (s.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(s) : s);

/** The function-like node of a declaration: function declaration, or arrow/function expression in a const (also inside forwardRef/memo calls). */
function fnOf(decl) {
  if (ts.isFunctionDeclaration(decl)) return decl;
  if (ts.isVariableDeclaration(decl) && decl.initializer) {
    let init = decl.initializer;
    while (ts.isCallExpression(init) && init.arguments.length) init = init.arguments[0];
    if (ts.isArrowFunction(init) || ts.isFunctionExpression(init)) return init;
  }
  return null;
}
const returnsJsx = (fn) => {
  let found = false;
  const visit = (n) => { if (found) return; if (ts.isJsxElement(n) || ts.isJsxSelfClosingElement(n) || ts.isJsxFragment(n)) { found = true; return; } ts.forEachChild(n, visit); };
  if (fn.body) visit(fn.body);
  return found;
};

/** Default values from a destructured first parameter: ({ a = 1, b: c = "x" }) => { a: "1", b: '"x"' } */
function defaultsOf(param) {
  const map = {};
  if (param && ts.isObjectBindingPattern(param.name)) {
    for (const el of param.name.elements) {
      if (!el.initializer) continue;
      const key = el.propertyName ? el.propertyName.getText().replace(/^["']|["']$/g, "") : el.name.getText();
      map[key] = clean(el.initializer.getText());
    }
  }
  return map;
}

const propsOfType = (type, defaults, notes) => {
  const props = [];
  for (const p of checker.getPropertiesOfType(type)) {
    const decl = p.declarations?.find(isOurs) ?? p.declarations?.[0];
    if (!decl || !isOurs(decl)) continue; // inherited from React, DOM or React Aria: not ours to document
    const node = decl;
    const typeText = ts.isPropertySignature(node) && node.type ? clean(node.type.getText()) : clean(checker.typeToString(checker.getTypeOfSymbolAtLocation(p, node), node, ts.TypeFormatFlags.NoTruncation | ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope));
    props.push({ name: p.getName(), type: typeText, required: !(p.flags & ts.SymbolFlags.Optional), default: defaults[p.getName()] ?? null, description: firstParagraph(p) });
  }
  const total = checker.getPropertiesOfType(type).length;
  if (total > props.length) notes.push(`${total - props.length} more props are inherited from HTML, ARIA or React Aria types and are not listed`);
  return props;
};

const synthValue = (p) => {
  const t = p.type;
  if (/^(string|"[^"]*")(\s*\|\s*"[^"]*")*$/.test(t) && t !== "string") return `${t.split("|")[0].trim()}`.replace(/^"|"$/g, (q) => q) ;
  if (t === "string") return '"…"';
  if (t === "number") return "{0}";
  if (t === "boolean") return "{true}";
  if (/=>/.test(t)) return "{() => {}}";
  if (/\[\]$|^Array</.test(t)) return "{[]}";
  if (/ReactNode|JSX\.Element/.test(t)) return "{<span>…</span>}";
  return "{…}";
};
const attr = (p) => { const v = synthValue(p); return v.startsWith('"') ? `${p.name}=${v}` : `${p.name}=${v}`; };
const synthesise = (name, kind, props, hasChildren) => {
  if (kind === "component") {
    const req = props.filter((p) => p.required && p.name !== "children");
    const a = req.map(attr).join(" ");
    return hasChildren ? `<${name}${a ? " " + a : ""}>…</${name}>` : `<${name}${a ? " " + a : ""} />`;
  }
  if (kind === "value") return `import { ${name} } from "@proshore/ui";`;
  if (kind === "hook") return `const result = ${name}(${props.filter((p) => p.required).map((p) => p.name).join(", ")});`;
  if (kind === "function") return `${name}(${props.filter((p) => p.required).map((p) => p.name).join(", ")});`;
  return `import type { ${name} } from "@proshore/ui";`;
};

const area = (name, kind, file) => {
  if (kind === "hook" || kind === "type" || kind === "value") return "Hooks and types";
  if (file === "icons.tsx") return "Icons";
  if (/^(AppShell|ShellNav|AppIcon|AppTitle|SherpaGuide|CommandPalette|AssistantPanel|AppHeader|WorkspaceSwitcher|UserMenu|ProshoreMenu|ProshoreTheme|SherpaTheme|PortalHost|ProshoreIcon|ProshoreWordmark|LocaleProvider|DemoTag)$/.test(name)) return "Shell";
  if (/^(SignInScreen|GoogleSignInButton|GoogleMark)$/.test(name)) return "Auth-free UI";
  if (file.startsWith("components/charts")) return "Charts";
  if (file.startsWith("components/table") || /^(SimpleTable|Pagination)$/.test(name)) return "Tables";
  if (file.startsWith("primitives/forms") || /^(FileDropzone)$/.test(name)) return "Forms";
  if (/^(SlideOver|SlideGroup|ModalDialog|ConfirmDialog|PopoverPanel|Tooltip|ToastHost|toast|CommandPalette)$/.test(name)) return "Overlays";
  if (/^(Button|IconButton|Breadcrumbs|Tabs|Stepper|Disclosure|KanbanBoard)$/.test(name)) return "Actions";
  return "Layout";
};

const items = [];
for (const exp of checker.getExportsOfModule(checker.getSymbolAtLocation(entry))) {
  const name = exp.getName();
  const sym = resolveSymbol(exp);
  const decls = sym.declarations ?? [];
  const decl = decls.find(isOurs) ?? decls[0];
  if (!decl || !isOurs(decl)) { items.push({ name, kind: "type", description: "", props: [], definition: null, area: "Hooks and types", snippetSource: "synthesised", file: "(external)", snippet: "", notes: ["could not resolve a declaration in this package"] }); continue; }
  const file = rel(decl);
  const notes = [];
  const isType = ts.isTypeAliasDeclaration(decl) || ts.isInterfaceDeclaration(decl);
  const fn = isType ? null : fnOf(decl);
  const isIcon = file === "icons.tsx";
  let kind = isType ? "type" : /^use[A-Z]/.test(name) ? "hook" : fn && /^[A-Z]/.test(name) ? "component" : fn ? "function" : /^[A-Z]/.test(name) ? "component" : "function";
  if (kind === "component" && !fn && !isIcon && !(ts.isVariableDeclaration(decl) && decl.initializer)) kind = "function";
  let props = [], hasChildren = false, definition = null, description = firstParagraph(sym);
  const example = exampleOf(sym);

  if (isType) {
    const type = checker.getDeclaredTypeOfSymbol(sym);
    const objectLike = ts.isInterfaceDeclaration(decl) || (ts.isTypeAliasDeclaration(decl) && (ts.isTypeLiteralNode(decl.type) || ts.isIntersectionTypeNode(decl.type)));
    if (objectLike) props = propsOfType(type, {}, notes);
    else if (ts.isTypeAliasDeclaration(decl)) definition = clean(decl.type.getText());
  } else if (fn) {
    const param = fn.parameters[0];
    if (kind === "component") {
      if (param) {
        props = propsOfType(checker.getTypeAtLocation(param), defaultsOf(param), notes);
        hasChildren = props.some((p) => p.name === "children");
        // the description often sits on the named props type (BarChartProps) rather than on the function
        if (!description && param.type && ts.isTypeReferenceNode(param.type)) { const ts2 = checker.getSymbolAtLocation(param.type.typeName); if (ts2) description = firstParagraph(resolveSymbol(ts2)); }
        if (!props.length && !notes.length && param.type) notes.push("props type could not be expanded");
      }
    } else {
      // hooks and functions: list parameters as "props"
      props = fn.parameters.map((p) => ({ name: p.name.getText().length > 30 ? "options" : p.name.getText(), type: p.type ? clean(p.type.getText()) : "unknown", required: !p.questionToken && !p.initializer, default: p.initializer ? clean(p.initializer.getText()) : null, description: "" }));
      if (fn.parameters.length === 1 && ts.isObjectBindingPattern(fn.parameters[0].name)) {
        props = propsOfType(checker.getTypeAtLocation(fn.parameters[0]), defaultsOf(fn.parameters[0]), notes);
      }
    }
  } else if (isIcon) {
    notes.push("accepts all SVG props (width and height default to 15)");
  } else if (kind === "function" || kind === "component") {
    // object values such as `toast`, or consts we cannot read as a function
    const t = checker.getTypeOfSymbolAtLocation(sym, decl);
    const sigs = t.getCallSignatures();
    if (sigs.length) props = sigs[0].getParameters().map((p) => ({ name: p.getName(), type: clean(checker.typeToString(checker.getTypeOfSymbolAtLocation(p, decl))), required: !(p.flags & ts.SymbolFlags.Optional), default: null, description: "" }));
    else { kind = "value"; definition = clean(checker.typeToString(t, decl, ts.TypeFormatFlags.NoTruncation)); }
  }
  if (isIcon) description = description || "Radix icon, drawn on a 15px grid in currentColor.";
  if (kind === "component" && !isIcon && !fn && !props.length) notes.push("not a plain function component (context or provider); props are not extracted");
  if (kind === "component" && !description) notes.push("no JSDoc description");
  items.push({ name, kind, area: area(name, kind, file), description, props, definition, file: `src/${file}`, snippet: example || synthesise(name, kind, props, hasChildren), snippetSource: example ? "example" : "synthesised", notes });
}
items.sort((a, b) => a.name.localeCompare(b.name));
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, JSON.stringify({ exports: items }, null, 2) + "\n");
const comps = items.filter((i) => i.kind === "component");
console.log(`api: ${items.length} exports (${comps.length} components, ${items.filter((i) => i.kind === "hook").length} hooks, ${items.filter((i) => i.kind === "function").length} functions, ${items.filter((i) => i.kind === "type").length} types), ${items.reduce((n, i) => n + i.props.length, 0)} props, ${items.filter((i) => i.snippetSource === "example").length} with @example -> ${relative(process.cwd(), out)}`);
